function setOutputFlagIcon() {
    $("#countryFlagOut").empty();

    const outputFlag = new Image();

    const countryCode = currencyToCountryCodeMap.get(outputSelectedCurrency) || 'unknown';
    outputFlag.src = `https://flagsapi.com/${countryCode}/shiny/32.png`;
    console.log(outputFlag)
    outputFlag.onload = function () {
        $("#countryFlagOut").append($(outputFlag).addClass("loaded"));
    };

    outputFlag.onerror = function () {
        $("#rateCurrencyOut").text(outputSelectedCurrency);
    };
}

function setInputFlagIcon() {
    $("#countryFlagIn").empty();
    const inputFlag = new Image();

    const countryCode = currencyToCountryCodeMap.get(inputSelectedCurrency) || 'unknown';
    inputFlag.src = `https://flagsapi.com/${countryCode}/shiny/32.png`;
    console.log(inputFlag)
    inputFlag.onload = function () {
        $("#countryFlagIn").append($(inputFlag).addClass("loaded"));
    };

    inputFlag.onerror = function () {
        $("#rateCurrencyIn").text(outputSelectedCurrency);
    };
}

// Uses .get() to retrieve values (currencyToCountryCodeMap.get("USD") → "US").
const currencyToCountryCodeMap = new Map([
    ["EUR", "EU"],
    ["USD", "US"],
    ["GBP", "GB"],
    ["AED", "AE"],
    ["AFN", "AF"],
    ["ALL", "AL"],
    ["AMD", "AM"],
    ["ANG", "CW"],
    ["AOA", "AO"],
    ["ARS", "AR"],
    ["AUD", "AU"],
    ["AWG", "AW"],
    ["AZN", "AZ"],
    ["BAM", "BA"],
    ["BBD", "BB"],
    ["BDT", "BD"],
    ["BGN", "BG"],
    ["BHD", "BH"],
    ["BIF", "BI"],
    ["BMD", "BM"],
    ["BND", "BN"],
    ["BOB", "BO"],
    ["BRL", "BR"],
    ["BSD", "BS"],
    ["BTN", "BT"],
    ["BWP", "BW"],
    ["BYN", "BY"],
    ["BZD", "BZ"],
    ["CAD", "CA"],
    ["CDF", "CD"],
    ["CHF", "CH"],
    ["CLP", "CL"],
    ["CNY", "CN"],
    ["COP", "CO"],
    ["CRC", "CR"],
    ["CUP", "CU"],
    ["CVE", "CV"],
    ["CZK", "CZ"],
    ["DJF", "DJ"],
    ["DKK", "DK"],
    ["DOP", "DO"],
    ["DZD", "DZ"],
    ["EGP", "EG"],
    ["ERN", "ER"],
    ["ETB", "ET"],
    ["FJD", "FJ"],
    ["FKP", "FK"],
    ["FOK", "FO"],
    ["GEL", "GE"],
    ["GGP", "GG"],
    ["GHS", "GH"],
    ["GIP", "GI"],
    ["GMD", "GM"],
    ["GNF", "GN"],
    ["GTQ", "GT"],
    ["GYD", "GY"],
    ["HKD", "HK"],
    ["HNL", "HN"],
    ["HRK", "HR"],
    ["HTG", "HT"],
    ["HUF", "HU"],
    ["IDR", "ID"],
    ["ILS", "IL"],
    ["IMP", "IM"],
    ["INR", "IN"],
    ["IQD", "IQ"],
    ["IRR", "IR"],
    ["ISK", "IS"],
    ["JEP", "JE"],
    ["JMD", "JM"],
    ["JOD", "JO"],
    ["JPY", "JP"],
    ["KES", "KE"],
    ["KGS", "KG"],
    ["KHR", "KH"],
    ["KID", "KI"],
    ["KMF", "KM"],
    ["KRW", "KR"],
    ["KWD", "KW"],
    ["KYD", "KY"],
    ["KZT", "KZ"],
    ["LAK", "LA"],
    ["LBP", "LB"],
    ["LKR", "LK"],
    ["LRD", "LR"],
    ["LSL", "LS"],
    ["LYD", "LY"],
    ["MAD", "MA"],
    ["MDL", "MD"],
    ["MGA", "MG"],
    ["MKD", "MK"],
    ["MMK", "MM"],
    ["MNT", "MN"],
    ["MOP", "MO"],
    ["MRU", "MR"],
    ["MUR", "MU"],
    ["MVR", "MV"],
    ["MWK", "MW"],
    ["MXN", "MX"],
    ["MYR", "MY"],
    ["MZN", "MZ"],
    ["NAD", "NA"],
    ["NGN", "NG"],
    ["NIO", "NI"],
    ["NOK", "NO"],
    ["NPR", "NP"],
    ["NZD", "NZ"],
    ["OMR", "OM"],
    ["PAB", "PA"],
    ["PEN", "PE"],
    ["PGK", "PG"],
    ["PHP", "PH"],
    ["PKR", "PK"],
    ["PLN", "PL"],
    ["PYG", "PY"],
    ["QAR", "QA"],
    ["RON", "RO"],
    ["RSD", "RS"],
    ["RUB", "RU"],
    ["RWF", "RW"],
    ["SAR", "SA"],
    ["SBD", "SB"],
    ["SCR", "SC"],
    ["SDG", "SD"],
    ["SEK", "SE"],
    ["SGD", "SG"],
    ["SHP", "SH"],
    ["SLE", "SL"],
    ["SLL", "SL"],
    ["SOS", "SO"],
    ["SRD", "SR"],
    ["SSP", "SS"],
    ["STN", "ST"],
    ["SYP", "SY"],
    ["SZL", "SZ"],
    ["THB", "TH"],
    ["TJS", "TJ"],
    ["TMT", "TM"],
    ["TND", "TN"],
    ["TOP", "TO"],
    ["TRY", "TR"],
    ["TTD", "TT"],
    ["TVD", "TV"],
    ["TWD", "TW"],
    ["TZS", "TZ"],
    ["UAH", "UA"],
    ["UGX", "UG"],
    ["UYU", "UY"],
    ["UZS", "UZ"],
    ["VES", "VE"],
    ["VND", "VN"],
    ["VUV", "VU"],
    ["WST", "WS"],
    ["XAF", "CF"],
    ["XCD", "AI"],
    ["XDR", "-"],
    ["XOF", "BJ"],
    ["XPF", "PF"],
    ["YER", "YE"],
    ["ZAR", "ZA"],
    ["ZMW", "ZM"]
]);

